name: "Slack Notify Build"
description: "Report GitHub Actions build status on Slack"
branding:
  icon: message-square
  color: orange
inputs:
  channel_id:
    description: "The Slack channel ID."
    required: true
  status:
    description: "The status to list in the update."
    required: true
  environment:
    description: "The environment of the deploy."
    required: true
  service_name:
    description: "Name of the service"
    required: true
  default_branch_name:
    description: "The default branch in the repo."
    required: true
  color:
    description: "The color of the Slack attachment."
    required: true
    default: "#cccccc"
  message_id:
    description: "The ID of the existing Slack message to update."
    required: false
outputs:
  message_id:
    description: "The unique timestamp identifier of the Slack message sent"
runs:
  using: "node20"
  main: "dist/index.js"
